# Form implementation generated from reading ui file 'bundle_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ManualBoxcar(object):
    def setupUi(self, ManualBoxcar):
        ManualBoxcar.setObjectName("ManualBoxcar")
        ManualBoxcar.resize(238, 76)
        self.gridLayout = QtWidgets.QGridLayout(ManualBoxcar)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=ManualBoxcar)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=ManualBoxcar)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=ManualBoxcar)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(ManualBoxcar)
        QtCore.QMetaObject.connectSlotsByName(ManualBoxcar)

    def retranslateUi(self, ManualBoxcar):
        _translate = QtCore.QCoreApplication.translate
        ManualBoxcar.setWindowTitle(_translate("ManualBoxcar", "Boxcar"))
        self.pushButton.setText(_translate("ManualBoxcar", "Get Value"))
        self.label.setText(_translate("ManualBoxcar", "Boxcar Manual Control"))
