# Form implementation generated from reading ui file 'canvas.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MplCanvas(object):
    def setupUi(self, MplCanvas):
        MplCanvas.setObjectName("MplCanvas")
        MplCanvas.resize(640, 500)
        self.gridLayout = QtWidgets.QGridLayout(MplCanvas)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=MplCanvas)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(MplCanvas)
        QtCore.QMetaObject.connectSlotsByName(MplCanvas)

    def retranslateUi(self, MplCanvas):
        _translate = QtCore.QCoreApplication.translate
        MplCanvas.setWindowTitle(_translate("MplCanvas", "Figure"))
