# Form implementation generated from reading ui file 'experiment_message.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExperimentMessage(object):
    def setupUi(self, ExperimentMessage):
        ExperimentMessage.setObjectName("ExperimentMessage")
        ExperimentMessage.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ExperimentMessage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=ExperimentMessage)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(parent=ExperimentMessage)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)

        self.retranslateUi(ExperimentMessage)
        QtCore.QMetaObject.connectSlotsByName(ExperimentMessage)

    def retranslateUi(self, ExperimentMessage):
        _translate = QtCore.QCoreApplication.translate
        ExperimentMessage.setWindowTitle(_translate("ExperimentMessage", "Experiment Message"))
        self.label.setText(_translate("ExperimentMessage", "Messages"))
