# Form implementation generated from reading ui file 'server.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Server(object):
    def setupUi(self, Server):
        Server.setObjectName("Server")
        Server.resize(460, 46)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Server)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name = QtWidgets.QLabel(parent=Server)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name.sizePolicy().hasHeightForWidth())
        self.name.setSizePolicy(sizePolicy)
        self.name.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.host = QtWidgets.QLineEdit(parent=Server)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.host.setFont(font)
        self.host.setObjectName("host")
        self.horizontalLayout.addWidget(self.host)
        self.port = QtWidgets.QLineEdit(parent=Server)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.port.setFont(font)
        self.port.setObjectName("port")
        self.horizontalLayout.addWidget(self.port)
        self.start = QtWidgets.QPushButton(parent=Server)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)
        self.test = QtWidgets.QPushButton(parent=Server)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.test.setFont(font)
        self.test.setObjectName("test")
        self.horizontalLayout.addWidget(self.test)
        self.status = QtWidgets.QLabel(parent=Server)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.status.setFont(font)
        self.status.setObjectName("status")
        self.horizontalLayout.addWidget(self.status)

        self.retranslateUi(Server)
        QtCore.QMetaObject.connectSlotsByName(Server)

    def retranslateUi(self, Server):
        _translate = QtCore.QCoreApplication.translate
        Server.setWindowTitle(_translate("Server", "Server"))
        self.name.setText(_translate("Server", "Server Name"))
        self.start.setText(_translate("Server", "Start"))
        self.test.setText(_translate("Server", "Test"))
        self.status.setText(_translate("Server", "OFF"))
