# Form implementation generated from reading ui file 'boxcar_preveiw.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BoxcarPreview(object):
    def setupUi(self, BoxcarPreview):
        BoxcarPreview.setObjectName("BoxcarPreview")
        BoxcarPreview.resize(562, 451)
        self.gridLayout = QtWidgets.QGridLayout(BoxcarPreview)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=BoxcarPreview)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=BoxcarPreview)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.widget = QtWidgets.QWidget(parent=BoxcarPreview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(540, 400))
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 2)

        self.retranslateUi(BoxcarPreview)
        QtCore.QMetaObject.connectSlotsByName(BoxcarPreview)

    def retranslateUi(self, BoxcarPreview):
        _translate = QtCore.QCoreApplication.translate
        BoxcarPreview.setWindowTitle(_translate("BoxcarPreview", "Boxcar Preview"))
        self.label.setText(_translate("BoxcarPreview", "Boxcar"))
        self.pushButton.setText(_translate("BoxcarPreview", "Acqire"))
