# Form implementation generated from reading ui file 'c:\Users\zhenggroup\Python\CB331\labctrl\components\power_meter\ophir\bundle_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ManualOphir(object):
    def setupUi(self, ManualOphir):
        ManualOphir.setObjectName("ManualOphir")
        ManualOphir.resize(238, 76)
        self.gridLayout = QtWidgets.QGridLayout(ManualOphir)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=ManualOphir)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=ManualOphir)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=ManualOphir)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(ManualOphir)
        QtCore.QMetaObject.connectSlotsByName(ManualOphir)

    def retranslateUi(self, ManualOphir):
        _translate = QtCore.QCoreApplication.translate
        ManualOphir.setWindowTitle(_translate("ManualOphir", "Ophir"))
        self.pushButton.setText(_translate("ManualOphir", "Get Value"))
        self.label.setText(_translate("ManualOphir", "Ophir Manual Control"))
