# Form implementation generated from reading ui file 'linear_stage_control.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LinearStageControlExperiment(object):
    def setupUi(self, LinearStageControlExperiment):
        LinearStageControlExperiment.setObjectName("LinearStageControlExperiment")
        LinearStageControlExperiment.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=LinearStageControlExperiment)
        self.centralwidget.setObjectName("centralwidget")
        LinearStageControlExperiment.setCentralWidget(self.centralwidget)

        self.retranslateUi(LinearStageControlExperiment)
        QtCore.QMetaObject.connectSlotsByName(LinearStageControlExperiment)

    def retranslateUi(self, LinearStageControlExperiment):
        _translate = QtCore.QCoreApplication.translate
        LinearStageControlExperiment.setWindowTitle(_translate("LinearStageControlExperiment", "Linear Stage Control"))
